{{- if .Values.ingress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-service
  annotations:
    cert-manager.io/cluster-issuer: yc-clusterissuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: webhook-service-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webhook-service
                port:
                  number: {{ .Values.server.port }}
{{- end }}
