apiVersion: v1
kind: Secret
metadata:
  name: webhook-service-secret
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  GH_WEBHOOK_SECRET: {{ .Values.secrets.githubWebhookSecret | quote }}
